version: 2.1

orbs:
    node: circleci/node@4.7

jobs:
    build_and_test:
        executor:
            name: node/default
            tag: '18.16.0'
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn
            - run:
                name: Build @devphase/service
                command: |
                    cd workspaces/service
                    yarn compile
            - run:
                name: Build @devphase/cli
                command: |
                    cd workspaces/cli
                    yarn compile
            - run:
                name: Reinstall all dependencies
                command: ./reinstall.sh
            - run:
                name: Run tests
                command: |
                    cd workspaces/cli-test
                    yarn test

workflows:
    test:
        jobs:
            - build_and_test
