version: 2.1

orbs:
    node: circleci/node@4.7

jobs:
    build_and_test:
        docker:
            - image: cimg/rust:1.68.2-node
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn
            - restore_cache:
                key: &deps1-cache deps1-{{ .Branch }}-3
            - run:
                name: Install cargo contract
                command: |
                    cargo install cargo-contract
                    rustup target add wasm32-unknown-unknown
                    rustup component add rust-src --toolchain 1.68.2-x86_64-unknown-linux-gnu
            - save_cache:
                key: *deps1-cache
                paths:
                    - "~/.cargo"
                    - "~/.rustup"
            - run:
                name: Build @devphase/service
                command: |
                    cd workspaces/service
                    yarn compile
            - run:
                name: Build @devphase/cli
                command: |
                    cd workspaces/cli
                    yarn compile
            - run:
                name: Reinstall all dependencies
                command: ./reinstall.sh
            - run:
                name: Run tests
                command: |
                    cd workspaces/cli-test
                    yarn test

workflows:
    test:
        jobs:
            - build_and_test
